export enum Icon {
  dns = 'dns',
  directions_car = 'directions_car',
  list_alt = 'list_alt',
  info = 'info',
  lock_open = 'lock_open',
  description = 'description',
  help = 'help',
  play_arrow = 'play_arrow',
  stop = 'stop',
  pause = 'pause',
  error = 'error',
  sync_problem = 'sync_problem',
  settings = 'settings',
  add = 'add',
  edit = 'edit',
  delete = 'delete',
  remove = 'remove',
  controller = 'sports_esports'
}
