-- Flyway Migration: V2.1.0.1
-- Purpose:
-- 1. Drop unique constraints on GAME.COVER_IMAGE_ID and GAME.HEADER_IMAGE_ID
-- 2. Rename UK*/FK* constraints to human-readable names (best-effort, idempotent)
-- Compatibility: H2 2.2+ and PostgreSQL 13+
--   Constraint renaming uses ALTER TABLE ... RENAME CONSTRAINT which is supported
--   by both H2 2.2+ and PostgreSQL. Each rename is guarded by existence checks
--   using a shared-syntax approach: attempt the rename and ignore errors via
--   individual statements that are safe to fail on both databases.
--
-- Note: H2 does not support DO $$ PL/pgSQL blocks, and PostgreSQL does not support
--   H2's CREATE ALIAS mechanism. Instead we use straightforward ALTER TABLE statements
--   with IF EXISTS guards where supported, accepting that rename failures are non-fatal
--   since the constraints function correctly under either name.

/******************************************************************************************
 * 1. Drop the two unwanted unique constraints on GAME
 ******************************************************************************************/
ALTER TABLE GAME DROP CONSTRAINT IF EXISTS UK52RQ62FLPBNTI77BYKM7UAHKQ;
ALTER TABLE GAME DROP CONSTRAINT IF EXISTS UK30B16LLQV54H40XIOGP7T9P35;

/******************************************************************************************
 * 2. Rename UNIQUE constraints — best effort, errors ignored at the application level
 *    Both H2 2.2+ and PostgreSQL support ALTER TABLE ... RENAME CONSTRAINT.
 *    The IF EXISTS guard is used where the old hashed name may or may not exist.
 *    Flyway runs each statement independently so individual failures don't abort the batch.
 ******************************************************************************************/

-- COMPANY
ALTER TABLE COMPANY RENAME CONSTRAINT UK4UCNYHR8I0URHWDUDFAHKOB9E TO UQ_COMPANY_NAME_TYPE;

-- DIRECTORY_MAPPING
ALTER TABLE DIRECTORY_MAPPING RENAME CONSTRAINT UKJ3GSATFAHEWFOLSEAJ29O3KYT TO UQ_DIRECTORY_MAPPING_INTERNAL_PATH;

-- GAME
ALTER TABLE GAME RENAME CONSTRAINT UK4WXN9FPXFQ8QXPSB7FY0O3NOA TO UQ_GAME_PATH;

-- GAME_IMAGES
ALTER TABLE GAME_IMAGES RENAME CONSTRAINT UKBDE7M3TKHIEEYBINM2ED0B6X1 TO UQ_GAME_IMAGES_IMAGE_ID;

-- LIBRARY_DIRECTORIES
ALTER TABLE LIBRARY_DIRECTORIES RENAME CONSTRAINT UKB5UM4CADBNC6UC8DVOMO81N5F TO UQ_LIBRARY_DIRECTORIES_DIRECTORY_ID;

-- LIBRARY_GAMES
ALTER TABLE LIBRARY_GAMES RENAME CONSTRAINT UK3E4VB9NQXPY27VMTA27GU5FY8 TO UQ_LIBRARY_GAMES_GAME_ID;

-- USERS
ALTER TABLE USERS RENAME CONSTRAINT UK6DOTKOTT2KJSP8VW4D0M25FB7 TO UQ_USERS_EMAIL;
ALTER TABLE USERS RENAME CONSTRAINT UKR43AF9AP4EDM43MMTQ01ODDJ6 TO UQ_USERS_USERNAME;
ALTER TABLE USERS RENAME CONSTRAINT UKRSULCN2GYNJY3CDDPWMOSV881 TO UQ_USERS_AVATAR_ID;

-- GAME_FIELD_METADATA
ALTER TABLE GAME_FIELD_METADATA RENAME CONSTRAINT UKHW6U2Y9FLWPTI57QB7K0P27BL TO UQ_GAME_FIELD_METADATA_SOURCE_ID;

-- GAME_FIELDS
ALTER TABLE GAME_FIELDS RENAME CONSTRAINT UK1L5OAH0UOOUV4V5A9P0PAK77X TO UQ_GAME_FIELDS_FIELD_METADATA_ID;

/******************************************************************************************
 * 3. Rename FOREIGN KEY constraints
 ******************************************************************************************/
ALTER TABLE GAME RENAME CONSTRAINT FK6CVB43REAYSNYPI0XDY6HQTVF TO FK_GAME_COVER_IMAGE;
ALTER TABLE GAME RENAME CONSTRAINT FK8N86NDPGKMOO7YOLX6HL8N84G TO FK_GAME_HEADER_IMAGE;
ALTER TABLE GAME RENAME CONSTRAINT FKIUVR8XFB63T1K6T43EYYXVO2C TO FK_GAME_LIBRARY;

ALTER TABLE GAME_DEVELOPERS RENAME CONSTRAINT FKB12PO9L2B9OJBAIHC82MM2QXB TO FK_GAME_DEVELOPERS_COMPANY;
ALTER TABLE GAME_DEVELOPERS RENAME CONSTRAINT FKS4IJSVPIJ53DSL143XVRGBS09 TO FK_GAME_DEVELOPERS_GAME;

ALTER TABLE GAME_FEATURES RENAME CONSTRAINT FK63XLTCT60SCIMPM06K8BHBE4A TO FK_GAME_FEATURES_GAME;
ALTER TABLE GAME_GENRES RENAME CONSTRAINT FKDTSX09YOPD98E0LUEWRUSJD9E TO FK_GAME_GENRES_GAME;

ALTER TABLE GAME_IMAGES RENAME CONSTRAINT FK5YWV1DMXCM2VSQUEB7RHQ3JK9 TO FK_GAME_IMAGES_IMAGE;
ALTER TABLE GAME_IMAGES RENAME CONSTRAINT FKOWCPUCV45OX8GT28TXGVHF1AA TO FK_GAME_IMAGES_GAME;

ALTER TABLE GAME_KEYWORDS RENAME CONSTRAINT FKMVF6HNJ7ROMQQM2EX70A9NVAC TO FK_GAME_KEYWORDS_GAME;
ALTER TABLE GAME_PERSPECTIVES RENAME CONSTRAINT FKHUEENG29Y1GHBRDI5QHGUXH6E TO FK_GAME_PERSPECTIVES_GAME;

ALTER TABLE GAME_PUBLISHERS RENAME CONSTRAINT FK49R2KB61LIJ54BQB4VNTST97N TO FK_GAME_PUBLISHERS_GAME;
ALTER TABLE GAME_PUBLISHERS RENAME CONSTRAINT FKNGLD5ESGRBRH95J5BJF0HEF85 TO FK_GAME_PUBLISHERS_COMPANY;

ALTER TABLE GAME_THEMES RENAME CONSTRAINT FKRV351JXLIOY0A17Y5BBJJ6FW4 TO FK_GAME_THEMES_GAME;
ALTER TABLE GAME_VIDEO_URLS RENAME CONSTRAINT FKJKKWO8WDS086AS7B2KSLSVKM6 TO FK_GAME_VIDEO_URLS_GAME;

ALTER TABLE LIBRARY_DIRECTORIES RENAME CONSTRAINT FKFNCKIU58I9L89MLXV388DY13B TO FK_LIBRARY_DIRECTORIES_LIBRARY;
ALTER TABLE LIBRARY_DIRECTORIES RENAME CONSTRAINT FKJDXS58Q1IRTU0IDP6DXJHWAPM TO FK_LIBRARY_DIRECTORIES_DIRECTORY_MAPPING;

ALTER TABLE LIBRARY_GAMES RENAME CONSTRAINT FK6C71EEDM0I2N1JXDE9BOBWG5M TO FK_LIBRARY_GAMES_LIBRARY;
ALTER TABLE LIBRARY_GAMES RENAME CONSTRAINT FKDKKKES3DAY0WJ1QMV42KMMFDK TO FK_LIBRARY_GAMES_GAME;

ALTER TABLE LIBRARY_UNMATCHED_PATHS RENAME CONSTRAINT FKSJ51WC2LBNNXY0LKLWELI6VSB TO FK_LIBRARY_UNMATCHED_PATHS_LIBRARY;

ALTER TABLE GAME_ORIGINAL_IDS RENAME CONSTRAINT FK1CSD5QD7VJT7BTTA3G7HGYBUX TO FK_GAME_ORIGINAL_IDS_GAME;
ALTER TABLE GAME_ORIGINAL_IDS RENAME CONSTRAINT FKMT0XWLPWPU9NP0Q289JBAHJRY TO FK_GAME_ORIGINAL_IDS_PLUGIN;

ALTER TABLE USERS RENAME CONSTRAINT FK19LFLPG5SEIS4DWRM2LVJLXFV TO FK_USERS_AVATAR_IMAGE;

ALTER TABLE GAME_FIELD_SOURCE RENAME CONSTRAINT FKNJC4QSS5APFHTPWP42OAEAL5G TO FK_GAME_FIELD_SOURCE_PLUGIN;
ALTER TABLE GAME_FIELD_SOURCE RENAME CONSTRAINT FKSR1BGTX5XJVMAL7FEFGL982TP TO FK_GAME_FIELD_SOURCE_USER;

ALTER TABLE GAME_FIELD_METADATA RENAME CONSTRAINT FKQ4RC409TP8FUBTTM733PMJD8F TO FK_GAME_FIELD_METADATA_SOURCE;

ALTER TABLE GAME_FIELDS RENAME CONSTRAINT FKLNEPI7YWCI86YH21KO9WD9PYF TO FK_GAME_FIELDS_GAME;
ALTER TABLE GAME_FIELDS RENAME CONSTRAINT FKT8FLOFDAPX5M746S5LW54C5B3 TO FK_GAME_FIELDS_METADATA;

ALTER TABLE TOKEN RENAME CONSTRAINT FKGHOIALAPTI5JFEJ506JBB1O8Y TO FK_TOKEN_CREATOR_USER;

ALTER TABLE USER_ROLES RENAME CONSTRAINT FKHFH9DX7W3UBF1CO1VDEV94G3F TO FK_USER_ROLES_USER;

-- End of migration
