-- Flyway Migration: V2.2.0.3
-- Purpose: Add LIBRARY_PLATFORMS and GAME_PLATFORMS tables to store list of associated platforms.
--          Add PLATFORM column to GAME_REQUEST table with default value for existing requests.
-- Compatibility: H2 2.2+ and PostgreSQL 13+ Fully compatible. Standard DDL and DML syntax.
--   TRIM() and <> '' work identically in PostgreSQL CHECK constraints.

CREATE TABLE LIBRARY_PLATFORMS
(
    LIBRARY_ID BIGINT       NOT NULL,
    PLATFORMS  VARCHAR(255) NOT NULL,
    CONSTRAINT PK_LIBRARY_PLATFORMS PRIMARY KEY (LIBRARY_ID, PLATFORMS),
    CONSTRAINT FK_LIBRARY_PLATFORMS_LIBRARY FOREIGN KEY (LIBRARY_ID) REFERENCES LIBRARY (ID) ON DELETE CASCADE,
    CONSTRAINT CK_LIBRARY_PLATFORMS_PLATFORM_NOT_EMPTY CHECK (TRIM(PLATFORMS) <> '')
);

CREATE TABLE GAME_PLATFORMS
(
    GAME_ID   BIGINT       NOT NULL,
    PLATFORMS VARCHAR(255) NOT NULL,
    CONSTRAINT PK_GAME_PLATFORMS PRIMARY KEY (GAME_ID, PLATFORMS),
    CONSTRAINT FK_GAME_PLATFORMS_GAME FOREIGN KEY (GAME_ID) REFERENCES GAME (ID) ON DELETE CASCADE,
    CONSTRAINT CK_GAME_PLATFORMS_PLATFORM_NOT_EMPTY CHECK (TRIM(PLATFORMS) <> '')
);

CREATE INDEX IDX_LIBRARY_PLATFORMS_LIBRARY_ID ON LIBRARY_PLATFORMS (LIBRARY_ID);
CREATE INDEX IDX_GAME_PLATFORMS_GAME_ID ON GAME_PLATFORMS (GAME_ID);

INSERT INTO LIBRARY_PLATFORMS (LIBRARY_ID, PLATFORMS)
SELECT ID, 'PC_MICROSOFT_WINDOWS'
FROM LIBRARY;

INSERT INTO GAME_PLATFORMS (GAME_ID, PLATFORMS)
SELECT ID, 'PC_MICROSOFT_WINDOWS'
FROM GAME;

ALTER TABLE GAME_REQUEST
    ADD COLUMN PLATFORM VARCHAR(255)
        NOT NULL
        DEFAULT 'PC_MICROSOFT_WINDOWS';
