-- Flyway Migration: V2.3.0.3
-- Purpose: Create COLLECTION and COLLECTION_GAMES tables for Collections feature.

CREATE SEQUENCE COLLECTION_SEQ INCREMENT BY 50;

CREATE TABLE COLLECTION (
    ID BIGINT NOT NULL PRIMARY KEY,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    NAME CHARACTER VARYING(255) NOT NULL UNIQUE,
    DESCRIPTION CHARACTER LARGE OBJECT
);

CREATE TABLE COLLECTION_GAMES (
    COLLECTION_ID BIGINT NOT NULL,
    GAME_ID BIGINT NOT NULL,
    PRIMARY KEY (COLLECTION_ID, GAME_ID),
    CONSTRAINT FK_COLLECTION_GAMES_COLLECTION FOREIGN KEY (COLLECTION_ID) REFERENCES COLLECTION ON DELETE CASCADE,
    CONSTRAINT FK_COLLECTION_GAMES_GAME FOREIGN KEY (GAME_ID) REFERENCES GAME ON DELETE CASCADE
);

-- Indexes to speed up lookup by GAME_ID and COLLECTION_ID
CREATE INDEX IDX_COLLECTION_GAMES_GAME_ID ON COLLECTION_GAMES (GAME_ID);
CREATE INDEX IDX_COLLECTION_GAMES_COLLECTION_ID ON COLLECTION_GAMES (COLLECTION_ID);

