-- Flyway Migration: V2.3.0.5
-- Purpose: Add tracking for when games are added to collections via COLLECTION_GAMES_ADDED_AT table.
-- Compatibility: H2 2.2+ and PostgreSQL 13+ Fully compatible. Standard DDL and INSERT ... SELECT syntax.

CREATE TABLE COLLECTION_GAMES_ADDED_AT
(
    COLLECTION_ID      BIGINT                   NOT NULL,
    GAMES_ADDED_AT_KEY BIGINT                   NOT NULL,
    GAMES_ADDED_AT     TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (COLLECTION_ID, GAMES_ADDED_AT_KEY),
    CONSTRAINT FK_COLLECTION_GAMES_ADDED_AT_COLLECTION FOREIGN KEY (COLLECTION_ID) REFERENCES COLLECTION ON DELETE CASCADE
);

CREATE INDEX IDX_COLLECTION_GAMES_ADDED_AT_COLLECTION_ID ON COLLECTION_GAMES_ADDED_AT (COLLECTION_ID);

INSERT INTO COLLECTION_GAMES_ADDED_AT (COLLECTION_ID, GAMES_ADDED_AT_KEY, GAMES_ADDED_AT)
SELECT CG.COLLECTIONS_ID, CG.GAMES_ID, C.CREATED_AT
FROM COLLECTION_GAMES CG
         JOIN COLLECTION C ON CG.COLLECTIONS_ID = C.ID;
