logging.level:
  root: warn
  org.atmosphere: warn
  org.gameyfin: info
  org.flywaydb.core.internal.command: info
  org.flywaydb.core.internal.sqlscript: warn
  org.gameyfin.GameyfinApplicationKt: warn
  # Suppress false positive warnings from Spring Security 6
  org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: error

server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie
      timeout: 4h
  forward-headers-strategy: framework
  jetty:
    threads:
      max: 20
      min: 4

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: restart, health, metrics, prometheus
  endpoint:
    pause:
      enabled: false
    restart:
      access: unrestricted
    health:
      group:
        readiness:
          include: pluginsLoaded

spring:
  application:
    name: Gameyfin
    version: @project.version@
  threads:
    virtual.enabled: true
  sql.init.mode: always
  datasource:
    username: gfadmin
    password: gameyfin
    db-name: gameyfin_db
    url: jdbc:h2:file:./db/${spring.datasource.db-name};CACHE_SIZE=16384
    driverClassName: org.h2.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 60_000
  flyway:
    baseline-on-migrate: true
    baseline-version: 2.0.0
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc.batch_size: 25
        order_inserts: true
        order_updates: true
  content:
    fs.filesystem-root: ./data/
  mvc:
    async.request-timeout: 0

vaadin:
  # To improve the performance during development.
  # For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
  allowed-packages:
    - com.vaadin
    - org.vaadin
    - dev.hilla
  pnpm:
    enable: false