logging.level:
  root: info
  org.gameyfin: debug
  org.gameyfin.app.GameyfinApplicationKt: info
  org.flywaydb.core.internal.database.base: warn

spring:
  datasource:
    url: jdbc:h2:file:./db/${spring.datasource.db-name};AUTO_SERVER=TRUE