name: Delete Docker Tag on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  delete-docker-tag:
    if: startsWith(github.event.pull_request.head.ref, 'fix/')
    runs-on: ubuntu-latest
    steps:
      - name: Extract merged branch name
        id: extract_branch
        run: |
          BRANCH="${{ github.event.pull_request.head.ref }}"
          TAG=${BRANCH#fix/}
          echo "tag=$TAG" >> $GITHUB_OUTPUT
        shell: bash

      - name: Delete Docker tag from Docker Hub
        if: steps.extract_branch.outputs.tag != ''
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          TAG: ${{ steps.extract_branch.outputs.tag }}
        run: |
          echo "Deleting Docker tag: $TAG"
          curl -X DELETE -u "$DOCKERHUB_USERNAME:$DOCKERHUB_TOKEN" \
            "https://hub.docker.com/v2/repositories/grimsi/gameyfin/tags/$TAG/"

